### ISSUE TITLE
wrong address issue on multiple gameservers 

### ISSUE THREAD

**Issue by FliesQQ** [zzsort/Aion-Version-Dll#14]
is there any possible to fixe wrong address issue on multiple gameservers ?

**Comment by artems37rus** [comment]
yes

**Comment by Wern-rm** [comment]
> yes

How?

**Comment by artems37rus** [comment]
> > yes
> 
> How?

![image](https://user-images.githubusercontent.com/50069281/99727521-273c7a00-2ac9-11eb-9116-aef7a4ee5008.png)

**Comment by Wern-rm** [comment]
> > > yes
> > 
> > 
> > How?
> 
> ![image](https://user-images.githubusercontent.com/50069281/99727521-273c7a00-2ac9-11eb-9116-aef7a4ee5008.png)

this solves the problem for a login server with multiple connections to game servers?

**Comment by Wern-rm** [comment]
@artems37rus Make a pull request so everyone knows this? This would be useful for the community

**Comment by FliesQQ** [comment]
> > > yes
> > 
> > 
> > How?
> 
> ![image](https://user-images.githubusercontent.com/50069281/99727521-273c7a00-2ac9-11eb-9116-aef7a4ee5008.png)

"Your ip" means the main server ip or sub server ip？

**Comment by artems37rus** [comment]
> @artems37rus Make a pull request so everyone knows this? This would be useful for the

I'll do it today.

**Comment by artems37rus** [comment]
> > > > yes
> > > 
> > > 
> > > How?
> > 
> > ![image](https://user-images.githubusercontent.com/50069281/99727521-273c7a00-2ac9-11eb-9116-aef7a4ee5008.png)
> 
> "Your ip" means the main server ip or sub server ip？

Yes, sub server ip

**Comment by artems37rus** [comment]
Made a pull request #15 
This is suitable for those who have a lot of servers
