### ISSUE TITLE
Windowed Mode problem

### ISSUE THREAD

**Issue by benas80** [zzsort/Aion-Version-Dll#4]
1.2 version(Windows 10) : windowed NOT working, full screen working 

1.1 version(Windows 10) : windowed working (but not perfect), full screen working 
1.0 version(Windows 10) : windowed working (but not perfect), full screen working 

Could You help to fix 1.2 version ?

**Comment by zzsort** [comment]
Sure, I can try. I will need start with some more details:

Which version of the client?
What is the full Windows version number? (run ver from console, or winver)
Can you describe the behavior of how its not working? Is it different than when it is not enabled? A video would be helpful, too.
Does version 1.1 work well enough that the game is playable for you, or is it still not usable?

**Comment by benas80** [comment]
winver: Windows 10: 1909
Client:  Aion 4.0.0.12
Not working (in windowed mode) like patch not included (as without Your patch), (but works in full screen, its strange)

1.1 version of this dll is working (w. mode to) but not perfect as in full screeen. (if You going with keys: W,S,A,D + Mouse moving there are some jumping screen, You know, if moving mouse alone its ok, but keys + mouse bring bad effects). In full screen its perfect.

**Comment by zzsort** [comment]
Uploaded version 1.3 which should fix this, so try that and let me know if it works. I noticed the bug starts the first time the window gets moved.

**Comment by benas80** [comment]
Hehe it works perfect now.
Great job.
Thanks.

**Comment by zzsort** [comment]
Cool, glad to hear it. Thanks for reporting!
