### ISSUE TITLE
can't useful for 5.8 and above

### ISSUE THREAD

**Issue by 14635956** [zzsort/Aion-Version-Dll#5]
can't useful for 5.8 and above
if u hava any free time wish u will look at 5.8 and above just need ip fix

**Comment by zzsort** [comment]
Aion 5.x works differently than 4.x, so it will take some time to understand how to make a fix. I will try to look into it someday, but no guarantees.

Here are some links for a different IP fix that should work for 5.8+ that you can use now:
https://spp-forum.de/viewtopic.php?f=2&t=19
https://github.com/AionGermany/aion-germany/blob/master/AL-Tools/AionLauncherEU_5.x.rar

**Comment by zzsort** [comment]
Try the new version 1.4, should work for 5.8

**Comment by 14635956** [comment]
god job  I tested  client china  RU  NA all  worked 
thanks your time
