### ISSUE TITLE
Mouse fix does not work = (

### ISSUE THREAD

**Issue by azraelim94** [zzsort/Aion-Version-Dll#6]
Thanks for the software, sorry for creating the theme, NOIP works for me, but the mouse fix does not work, I use the client 4.8  cc=7

**Comment by zzsort** [comment]
Did you add -win10-mouse-fix to the command line? The No-IP is on by default, and other features such as the mouse fix need to be turned on

**Comment by azraelim94** [comment]
In bat file?

**Comment by azraelim94** [comment]
Thank you very much, it works, I just did not know what should be indicated in the batch file.
