### ISSUE TITLE
mousefix stop working after transferring locations

### ISSUE THREAD

**Issue by flroexus** [zzsort/Aion-Version-Dll#8]
mousefix stop working after transferring locations mostly using return. go fullscreen and back to window mode does not fix it. need to relaunch game

**Comment by benas80** [comment]
Agreed, mousefix stop working after teleports. If You teleport to Altgard and You hold right mouse button and you still moving mouse (before new map is fully loaded),  mousefix stop working.

**Comment by Jonathan57500** [comment]
It is working as expected when full mode screen, you will have this issue only in windowed mode

**Comment by flroexus** [comment]
fixed
